# Generated by Django 4.2.4 on 2023-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favproducts_user_fav_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='favproducts',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
