# Generated by Django 4.2.4 on 2023-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favproducts_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favproducts',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favproducts',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
