# Generated by Django 4.2.4 on 2023-08-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_favproducts_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_products',
        ),
    ]
