# Generated by Django 4.2.4 on 2023-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
            ],
        ),
    ]
