# Generated by Django 4.2.4 on 2023-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_alter_product_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.CharField(default='', max_length=100),
        ),
    ]
