# Generated by Django 4.2.4 on 2023-08-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_product_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
