# Generated by Django 4.2.4 on 2023-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0004_favproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favproducts',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favproducts',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
